name: rci
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy=1.26
  - pandas=2.2
  - geopandas=1.0
  - shapely=2.0
  - rasterio=1.4
  - xarray=2024.11
  - netcdf4=1.7
  - networkx=3.4
  - pyogrio=0.10
